#pragma once

#include <string>
#include <filesystem>
#include <unordered_map>

// handles filesystem related tasks for dynamic Script linking
// this is a separate class from ScriptCompiler because Windows.h interferes with std::filesystem
//
// Script headers are found anywhere inside the project (the header's stem is the script's name),
// everything generated by the build goes to <project>/.vesta/build

class ScriptLoader {
public:
	// clang-cl command line, run with the executable's directory as the working directory
	// false if the scripts can't be built (no project, two scripts with the same name)
	static bool buildCompileCommandString(std::wstring& outCommand);

	static void clearScriptCache() { sourcePaths.clear(); headerPaths.clear(); }
	static bool buildDLLSourceFile();
	static bool replaceOldDLLFile();
	static bool scriptsDLLExists();

	static std::filesystem::path getBuildDirectory();
	static std::filesystem::path getDLLPath();

	static bool isScriptSourceFile(const std::filesystem::path& path);

private:
	// false if two script headers share a name
	static bool loadScriptPaths();

	// absolute paths, keyed by script name
	static std::unordered_map<std::string, std::filesystem::path> sourcePaths;
	static std::unordered_map<std::string, std::filesystem::path> headerPaths;
};
